name: ❌ Slicing Failed
description: When you see the message Slicing failed with an unexpected error
labels: ["Type: Bug", "Status: Triage", "Slicing Error :collision:"]
body:
- type: markdown
  attributes:
    value: |
       ### Project File
       **⚠️ Before you continue, we need your project file to troubleshoot a slicing crash.**
       It contains the printer and settings we need for troubleshooting. 
       
       ![Alt Text](https://user-images.githubusercontent.com/40423138/240616958-5a9751f2-bd34-4808-9752-6fde2e27516e.gif)
       
       To save a project file go to File -> Save project. 
       Please make sure to .zip your project file. 
       For big files, you may need to use [WeTransfer](https://wetransfer.com/) or similar file-sharing sites.
       
       🤔 Before you share, please think to yourself. Is this a model that can be shared?
           Unfortunately we cannot help if this file is missing. 
           Do you have the project file? Than let's continue ⬇️

       ### Questions
- type: input
  attributes:
    label: Cura Version
    placeholder: 5.3.1
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      We work hard on improving our slicing crashes. Our most recent release is 5.3.1.
      If you are not on the latest version of Cura, [you can download it here](https://github.com/Ultimaker/Cura/releases/tag/5.3.1)
- type: input
  attributes:
    label: Operating System
    description: Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.
    placeholder: Windows 11 / MacOS Catalina / MX Linux 
  validations:
    required: true
- type: input
  attributes:
    label: Printer
    description: Which printer was selected in Cura?
  validations:
    required: true
- type: input
  attributes:
    label: Name abnormal settings
    description: Are there any settings that you might have changed that caused the crash? Does your model slice when you select the default profiles?
    placeholder:
  validations:
- type: input
  attributes:
    label: Describe model location
    description: Does your model slice if you rotate the model 90 degrees or if you move it away from the center of the buildplate? 
    placeholder:
  validations:
- type: input
  attributes:
    label: Describe your model
    description: Have you sliced your model succesfully before? Is it watertight? Have you tried doing a quick [Mesh Fix with the Meshtools Plugin](https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools)? 
  validations:
    required: true
- type: textarea
  attributes:
    label: Add your .zip here ⬇️ 
    description: You can add the zip file and additional information that is relevant to the issue in the comments below.
  validations:
    required: true

